### PR TITLE
Improve tmark verification MPV handling

### LINKED ISSUE #28: Stop opening new mpv processes when verifying transitions
When verifying breaks, at:

https://github.com/SuperLesson/SuperLesson/blob/6a74322a12d419f5acd9636456a8a11d7472f179/src/main.py#L22

The script opens mpv repeatedly, instead of using the same process. Make it seek to the appropriate times instead.

### LINKED ISSUE #31: Split functionality into poetry commands
As it currently stands, the scripts are executed by running:

`poetry run python src/main.py [lesson-id]`

This runs all the scripts in sequence, which can be undesirable. Ideally, we should be able to run each task separately.

This can be done in poetry with the execution of specific commands, such as:

`poetry run transcribe`
`poetry run transitions`

This is documented [here](https://python-poetry.org/docs/cli/#run).

### PR DESCRIPTION
**Pull request by rsgrava**
This PR closes #28 by importing the python-mpv library to instantiate mpv and have it seek rather than close and restart.

### CODE REVIEW

**Comment by isinyaaa** [comment]
[1/4] is superseeded by #34 and [2/4] should come rather come in a separate PR, where we can discuss the interface we want for this. Please rename this PR so that it reflects only [3/4] and [4/4] (also please squash them) and remove other commits from the series.

**Review by isinyaaa — APPROVED** [review]
LGTM!

**Comment by alvesisaque** [comment]
Can you please verify that the cursor doesn't move (i.e. change focus) when seeking?

**Comment by isinyaaa** [comment]
Also please update the description. I'm not sure but it might close some unrelated issues as it stands.

**Comment by rsgrava** [comment]
The cursor stays unchanged and the description's been altered. May we merge this?

**Comment by isinyaaa** [comment]
Let's go.

**Pull request merged**
